language: php

php:
  - 7.4

env:
  - NODEJS_VERSION=12.18.3
  - NPM_VERSION=6.14.6

before_script:
  - dpkg -l
  - cp .env.example .env
  - mysql -e 'create database medical;'
  - mysql -u root -h 127.0.0.1 -e "SHOW DATABASES"
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('secret')"
  - composer install
  #composer install --prefer-dist --no-interaction
  - php artisan key:generate
  - cat .env
  - nvm install $NODEJS_VERSION
  - npm install
  - npm run dev
  - php artisan migrate --seed --no-interaction
  - ls -la

script:
  - vendor/bin/phpunit
